export const projects = [
 {
    title: "Powell Dr - RALEIGH, NC",
    description:
      "Integrated dinning with kitchen. New bathrooms. LVP flooring. Add attic living space. New lighting. All new appliances. New deck",
    beforeImgs: [
     "/images/Powell-before/1.jpeg",
     "/images/Powell-before/2.jpeg",
     "/images/Powell-before/3.jpeg",
     "/images/Powell-before/4.jpeg",
     "/images/Powell-before/5.jpeg",
     "/images/Powell-before/6.jpeg",
     "/images/Powell-before/7.jpeg",
     "/images/Powell-before/8.jpeg",
     "/images/Powell-before/9.jpeg",
     "/images/Powell-before/10.jpeg",
   ],
   afterImgs: [
     "/images/Powell-after/0.jpeg",
     "/images/Powell-after/1.jpg",
     "/images/Powell-after/2.jpg",
     "/images/Powell-after/3.jpg",
     "/images/Powell-after/4.jpg",
     "/images/Powell-after/5.jpg",
     "/images/Powell-after/6.jpg",
     "/images/Powell-after/7.jpg",
     "/images/Powell-after/8.jpg",
     "/images/Powell-after/9.jpg",
     "/images/Powell-after/10.jpg",
     "/images/Powell-after/11.jpg",
     "/images/Powell-after/12.jpg",
     "/images/Powell-after/13.jpg",
     "/images/Powell-after/14.jpg",
     "/images/Powell-after/15.jpg",
     "/images/Powell-after/16.jpeg",
    ],
  },
 {
    title: "Hartsfield Dr - WAKE FOREST, NC",
    description:
      "Total renovation. Flooring repair. New LVP. Siding. Room. Bathrooms. Kitchen. Oepned up living aread. New bathroom. New lighting. All new appliances. New front and back decks. Landscaping. New septic",
    beforeImgs: [
     "/images/Harstfield-before/1.jpeg",
"/images/Harstfield-before/2.jpeg",
"/images/Harstfield-before/3.jpeg",
"/images/Harstfield-before/4.jpeg",
"/images/Harstfield-before/5.jpeg",
"/images/Harstfield-before/6.jpeg",
"/images/Harstfield-before/7.jpeg",
"/images/Harstfield-before/8.jpeg",
"/images/Harstfield-before/9.jpeg",
"/images/Harstfield-before/10.jpeg",
"/images/Harstfield-before/11.jpeg",
"/images/Harstfield-before/12.jpeg",
"/images/Harstfield-before/13.jpeg",
"/images/Harstfield-before/14.jpeg",
"/images/Harstfield-before/15.jpeg",
"/images/Harstfield-before/16.jpeg",
"/images/Harstfield-before/17.jpeg",
"/images/Harstfield-before/18.jpeg",
"/images/Harstfield-before/19.jpeg",
"/images/Harstfield-before/20.jpeg",
   ],
   afterImgs: [
     "/images/Hartsfield-after/0.jpeg",
"/images/Hartsfield-after/1.jpeg",
"/images/Hartsfield-after/2.jpeg",
"/images/Hartsfield-after/3.jpeg",
"/images/Hartsfield-after/4.jpeg",
"/images/Hartsfield-after/5.jpeg",
"/images/Hartsfield-after/6.jpeg",
"/images/Hartsfield-after/7.jpeg",
"/images/Hartsfield-after/8.jpeg",
"/images/Hartsfield-after/9.jpeg",
"/images/Hartsfield-after/10.jpeg",
"/images/Hartsfield-after/15.jpeg",
"/images/Hartsfield-after/20.jpeg",
"/images/Hartsfield-after/30.jpeg",
"/images/Hartsfield-after/40.jpeg",
"/images/Hartsfield-after/45.jpeg",
"/images/Hartsfield-after/50.jpeg",
"/images/Hartsfield-after/55.jpeg",
"/images/Hartsfield-after/60.jpeg",
"/images/Hartsfield-after/65.jpeg",
    ],
  },
   {
    title: "Joel Ct - CARY, NC",
    description:
      "Opened up kitchen. New hardwood flooring. Remodeled bathrooms, landscaping, new lighting. All new appliances.",
    beforeImgs: [
      "/images/Joel-before/7.jpeg",
      "/images/Joel-before/3.jpeg",
      "/images/Joel-before/2.jpeg",
      "/images/Joel-before/4.jpeg",
      "/images/Joel-before/5.jpeg",
      "/images/Joel-before/6.jpeg",
      "/images/Joel-before/1.jpeg",
    ],
    afterImgs: [
      "/images/Joel-after/1.jpeg",
      "/images/Joel-after/2.jpeg",
      "/images/Joel-after/5.jpeg",
      "/images/Joel-after/6.jpeg",
      "/images/Joel-after/7.jpeg",
      "/images/Joel-after/8.jpeg",
      "/images/Joel-after/9.jpeg",
      "/images/Joel-after/10.jpeg",
      "/images/Joel-after/11.jpeg",
      "/images/Joel-after/3.jpeg",
      "/images/Joel-after/4.jpeg",
    ],
  },
  {
    title: "Caniff Ln - CARY, NC",
    description:
      "On this house we have installed all new hardwood floors, kitchen cabinets, lighting, paint, bathrooms, outdoor patio, landscaping.",
    beforeImgs: [
      "/images/Caniff-before/1.jpeg",
      "/images/Caniff-before/4.jpeg",
      "/images/Caniff-before/5.jpeg",
      "/images/Caniff-before/6.jpeg",
      "/images/Caniff-before/7.jpeg",
      "/images/Caniff-before/10.jpeg",
      "/images/Caniff-before/2.jpeg",
      "/images/Caniff-before/3.jpeg",
      "/images/Caniff-before/8.jpeg",
      "/images/Caniff-before/9.jpeg",
    ],
    afterImgs: [
      "/images/Caniff-after/1.jpeg",
      "/images/Caniff-after/2.jpeg",
      "/images/Caniff-after/3.jpeg",
      "/images/Caniff-after/4.jpeg",
      "/images/Caniff-after/5.jpeg",
      "/images/Caniff-after/6.jpeg",
      "/images/Caniff-after/7.jpeg",
      "/images/Caniff-after/8.jpeg",
      "/images/Caniff-after/9.jpeg",
      "/images/Caniff-after/10.jpeg",
      "/images/Caniff-after/11.jpeg",
      "/images/Caniff-after/12.jpeg",
      "/images/Caniff-after/13.jpeg",
      "/images/Caniff-after/14.jpeg",
      "/images/Caniff-after/15.jpeg",
      "/images/Caniff-after/16.jpeg",
      "/images/Caniff-after/17.jpeg",
    ],
  },
  {
    title: "Wyman Pl - DURHAM, NC",
    description:
      "Integrated kitchen, new door to new deck. New hardwood flooring. Remodeled bathrooms, landscaping, new fence. All new appliances. Encapsulated crawl space.",
    beforeImgs: [
      "/images/Wyman-before/1.jpeg",
      "/images/Wyman-before/2.jpeg",
      "/images/Wyman-before/3.jpeg",
      "/images/Wyman-before/4.jpeg",
      "/images/Wyman-before/5.jpeg",
      "/images/Wyman-before/6.jpeg",
      "/images/Wyman-before/7.jpeg",
      "/images/Wyman-before/8.jpeg",
      "/images/Wyman-before/9.jpeg",
      "/images/Wyman-before/10.jpeg",
    ],
    afterImgs: [
      "/images/Wyman-after/1.jpeg",
      "/images/Wyman-after/2.jpeg",
      "/images/Wyman-after/3.jpeg",
      "/images/Wyman-after/4.jpeg",
      "/images/Wyman-after/5.jpeg",
      "/images/Wyman-after/6.jpeg",
      "/images/Wyman-after/7.jpeg",
      "/images/Wyman-after/8.jpeg",
      "/images/Wyman-after/9.jpeg",
      "/images/Wyman-after/10.jpeg",
      "/images/Wyman-after/11.jpeg",
      "/images/Wyman-after/12.jpeg",
      "/images/Wyman-after/13.jpeg",
    ],
  },
];
