export const projects = [
  {
    title: "Pine Mountain Dr",
    location: "HOUSTON, NC",
    tagline: "A Complete Comeback from Disaster",
    description:
      "After hurricane flooding, this home was rebuilt from the ground up—every bedroom, bath, and living space restored and upgraded. We delivered a brand new layout with an office, stylish dining, enhanced lighting, fresh insulation, and major curb appeal with new garage, siding, and brickwork. The transformation turned tragedy into a welcoming, modern family home.",
    beforeImgs: [
      "/images/Pine Mountain-before/IMG_3196.jpeg",
      "/images/Pine Mountain-before/IMG_3204.jpeg",
      "/images/Pine Mountain-before/IMG_3205.jpeg",
      "/images/Pine Mountain-before/IMG_3206.jpeg",
      "/images/Pine Mountain-before/IMG_3207.jpeg",
      "/images/Pine Mountain-before/IMG_3208.jpeg",
      "/images/Pine Mountain-before/IMG_3209.jpeg",
      "/images/Pine Mountain-before/IMG_3210.jpeg",
      "/images/Pine Mountain-before/IMG_3211.jpeg",
      "/images/Pine Mountain-before/IMG_3212.jpeg",
      "/images/Pine Mountain-before/IMG_3213.jpeg",
      "/images/Pine Mountain-before/IMG_3214.jpeg",
      "/images/Pine Mountain-before/IMG_3215.jpeg",
      "/images/Pine Mountain-before/IMG_3216.jpeg",
      "/images/Pine Mountain-before/IMG_3217.jpeg",
      "/images/Pine Mountain-before/IMG_3218.jpeg",
      "/images/Pine Mountain-before/IMG_3219.jpeg",
      "/images/Pine Mountain-before/IMG_3220.jpeg",
      "/images/Pine Mountain-before/IMG_3221.jpeg",
      "/images/Pine Mountain-before/IMG_3224.jpeg",
    ],
    afterImgs: [
      "/images/Pine Mountain-after/1.jpeg",
      "/images/Pine Mountain-after/20.jpeg",
      "/images/Pine Mountain-after/30.jpeg",
      "/images/Pine Mountain-after/40.jpeg",
      //"/images/Pine Mountain-after/45.jpeg",
      "/images/Pine Mountain-after/50.jpeg",
      "/images/Pine Mountain-after/60.jpeg",
    ],
  },
  {
    title: "Blanca Springs Ct",
    location: "HOUSTON, NC",
    tagline: "Restored & Renewed After the Flood",
    description:
      "Every inch of this home was renewed after major flood damage. From brand new walls and floors to fresh paint, cabinets, and vanities, we delivered a “like new” space that’s ready for years of comfortable living.",
    beforeImgs: [
      "/images/Blanca Springs-before/IMG_4039.jpeg",
      "/images/Blanca Springs-before/IMG_4040.jpeg",
      "/images/Blanca Springs-before/IMG_4042.jpeg",
      "/images/Blanca Springs-before/IMG_4043.jpeg",
      "/images/Blanca Springs-before/IMG_4044.jpeg",
      "/images/Blanca Springs-before/IMG_4046.jpeg",
      "/images/Blanca Springs-before/IMG_4053.jpeg",
      "/images/Blanca Springs-before/IMG_4054.jpeg",
      "/images/Blanca Springs-before/IMG_4058.jpeg",
      "/images/Blanca Springs-before/IMG_4061.jpeg",
    ],
    afterImgs: [
      "/images/Blanca Springs-after/img-1.jpeg",
      "/images/Blanca Springs-after/img-4.jpeg",
      "/images/Blanca Springs-after/img-6.jpeg",
      "/images/Blanca Springs-after/img-9.jpeg",
    ],
  },
  {
    title: "Welcome Dr",
    location: "DURHAM, NC",
    tagline: "A Classic Ranch, Totally Reimagined",
    description:
      "We took a tired 1960s ranch house and brought it into the modern era—opening up spaces, installing hardwood floors, sleek new kitchen and baths, attic living space, and modern lighting throughout. Now it’s an inviting home with plenty of room to live, work, and relax.",
    beforeImgs: [
      "/images/Welcome-before/1.jpeg",
      "/images/Welcome-before/2.jpeg",
      "/images/Welcome-before/3.jpeg",
      "/images/Welcome-before/4.jpeg",
      "/images/Welcome-before/5.jpeg",
      "/images/Welcome-before/6.jpeg",
      "/images/Welcome-before/7.jpeg",
      "/images/Welcome-before/8.jpeg",
      "/images/Welcome-before/9.jpeg",
      "/images/Welcome-before/10.jpeg",
      "/images/Welcome-before/11.jpeg",
      "/images/Welcome-before/12.jpeg",
      //"/images/Welcome-before/13.jpeg",
    ],
    afterImgs: [
      "/images/Welcome-after/0.jpg",
      "/images/Welcome-after/110.jpg",
      //"/images/Welcome-after/112.jpg",
      //"/images/Welcome-after/115.jpg",
      "/images/Welcome-after/130.jpg",
      "/images/Welcome-after/135.jpg",
      "/images/Welcome-after/140.jpg",
      //"/images/Welcome-after/145.jpg",
      "/images/Welcome-after/147.jpg",
      //"/images/Welcome-after/149.jpg",
      "/images/Welcome-after/152.jpg",
      "/images/Welcome-after/155.jpg",
      //"/images/Welcome-after/160.jpg",
      //"/images/Welcome-after/170.jpg",
      "/images/Welcome-after/172.jpg",
      //"/images/Welcome-after/174.jpg",
      "/images/Welcome-after/176.jpg",
      "/images/Welcome-after/178.jpg",
      "/images/Welcome-after/180.jpg",
      "/images/Welcome-after/200.jpg",
      "/images/Welcome-after/210.jpg",
    ],
  },
  {
    title: "Powell Dr",
    location: "RALEIGH, NC",
    tagline: "Modern, Bright, and Family-Ready",
    description:
      "We created an open and airy layout with a beautiful kitchen, luxury vinyl flooring, skylit attic living, and modern bathrooms. The finishing touch? A new deck for outdoor gatherings—making this the perfect home for busy families and entertaining.",
    beforeImgs: [
      "/images/Powell-before/1.jpeg",
      "/images/Powell-before/2.jpeg",
      "/images/Powell-before/3.jpeg",
      "/images/Powell-before/4.jpeg",
      "/images/Powell-before/5.jpeg",
      "/images/Powell-before/6.jpeg",
      "/images/Powell-before/7.jpeg",
      "/images/Powell-before/8.jpeg",
      "/images/Powell-before/9.jpeg",
      "/images/Powell-before/10.jpeg",
    ],
    afterImgs: [
      "/images/Powell-after/0.jpeg",
      //"/images/Powell-after/1.jpg",
      //"/images/Powell-after/2.jpg",
      "/images/Powell-after/3.jpg",
      "/images/Powell-after/4.jpg",
      "/images/Powell-after/5.jpg",
      "/images/Powell-after/6.jpg",
      //"/images/Powell-after/7.jpg",
      "/images/Powell-after/8.jpg",
      "/images/Powell-after/9.jpg",
      "/images/Powell-after/10.jpg",
      "/images/Powell-after/11.jpg",
      "/images/Powell-after/12.jpg",
      "/images/Powell-after/13.jpg",
      "/images/Powell-after/14.jpg",
      //"/images/Powell-after/15.jpg",
      "/images/Powell-after/16.jpeg",
    ],
  },{
    title: "Piendmont Av",
    location: "DURHAM, NC",
    tagline: "Spacious, Stylish, Effortless Living",
    description:
      "This custom-built Durham home features spacious rooms, an open living area, and a dedicated office—perfect for work and relaxation. Our project focused on cosmetic upgrades: we repainted the walls, refinished the floors, and enhanced the outdoor spaces by adding a new front fence and fresh grass in the backyard. The result is a welcoming home with great flow and inviting green spaces, ideal for everyday living and entertaining.",
    beforeImgs: [
      "/images/Piedmont-before/1.jpg",
      "/images/Piedmont-before/2.jpg",
      "/images/Piedmont-before/3.jpg",
      
    ],
    afterImgs: [
      "/images/Piedmont-after/1.jpeg",
"/images/Piedmont-after/2.jpeg",
"/images/Piedmont-after/3.jpeg",
"/images/Piedmont-after/4.jpeg",
"/images/Piedmont-after/5.jpeg",
"/images/Piedmont-after/6.jpeg",
"/images/Piedmont-after/7.jpeg",
"/images/Piedmont-after/8.jpeg",
"/images/Piedmont-after/9.jpeg",
"/images/Piedmont-after/10.jpeg",
"/images/Piedmont-after/11.jpeg",
"/images/Piedmont-after/12.jpeg",
"/images/Piedmont-after/13.jpeg",
"/images/Piedmont-after/14.jpeg",
"/images/Piedmont-after/15.jpeg",
"/images/Piedmont-after/16.jpeg",
"/images/Piedmont-after/17.jpeg",
"/images/Piedmont-after/18.jpeg",
"/images/Piedmont-after/19.jpeg",
"/images/Piedmont-after/20.jpeg",
"/images/Piedmont-after/21.jpeg",
"/images/Piedmont-after/22.jpeg",
"/images/Piedmont-after/23.jpeg",
"/images/Piedmont-after/24.jpeg",
"/images/Piedmont-after/25.jpeg",
"/images/Piedmont-after/26.jpeg",
"/images/Piedmont-after/27.jpeg",
"/images/Piedmont-after/28.jpeg",
"/images/Piedmont-after/29.jpeg",
"/images/Piedmont-after/30.jpeg",
"/images/Piedmont-after/31.jpeg",

      
    ],
  },{
    title: "Regency Cottage Pl",
    location: "CARY, NC",
    tagline: "Exclusive Living, Elevated",
    description:
      "Nestled in an exclusive, private Cary subdivision, this custom-built home already stood out with its soaring 10-foot ceilings and quiet elegance. We refreshed its beauty inside and out: painting every wall, refinishing the floors, updating the carpet, adding a brand new deck, and giving the kitchen cabinets a fresh, modern look. The result is a move-in-ready home that feels both luxurious and inviting—perfect for those seeking comfort and style in a private setting.",
    beforeImgs: [
      "/images/Regency-before/1.jpg",
      "/images/Regency-before/2.jpg",
      "/images/Regency-before/3.jpg",
      
    ],
    afterImgs: [
      "/images/Regency-after/1.jpeg",
      "/images/Regency-after/2.jpeg",
      "/images/Regency-after/3.jpeg",
      "/images/Regency-after/4.jpeg",
      "/images/Regency-after/5.jpeg",
      "/images/Regency-after/6.jpeg",

      
    ],
  },
  {
    title: "Carlisle St",
    location: "RALEIGH, NC",
    tagline: "Rebuilt for a Fresh Start",
    description:
      "On this large Raleigh lot, we completely redesigned the home—new flooring, modern kitchen, beautiful bathrooms, an added office and bedroom, and a smart, spacious layout for easy living.",
    beforeImgs: [
      "/images/Carlisle-before/2410509-4.jpeg",
      "/images/Carlisle-before/2410509-5.jpeg",
      "/images/Carlisle-before/2410509-6.jpeg",
      "/images/Carlisle-before/IMG_4259.jpeg",
      "/images/Carlisle-before/IMG_4270.jpeg",
      "/images/Carlisle-before/IMG_4292.jpeg",
      "/images/Carlisle-before/IMG_4295.jpeg",
    ],
    afterImgs: [
      "/images/Carlisle-after/0.jpg",
      "/images/Carlisle-after/1.jpg",
      "/images/Carlisle-after/5.jpg",
      "/images/Carlisle-after/06.jpg",
      "/images/Carlisle-after/07.jpg",
      "/images/Carlisle-after/6.jpg",
      "/images/Carlisle-after/7.jpg",
      "/images/Carlisle-after/8.jpg",
      "/images/Carlisle-after/20.jpg",
      "/images/Carlisle-after/50.jpg",
    ],
  },
  {
    title: "Crafton Park Ln",
    location: "CARY, NC",
    tagline: "Space for Family & Guests—Top to Bottom!",
    description:
      "This Cary attic was transformed into a stunning guest suite, complete with a bathroom and insulated garage. We also refreshed the master bath and created new laundry and storage rooms—maximizing comfort and convenience for the whole family.",
    beforeImgs: [
      "/images/Crafton Park-before/1.jpeg",
      "/images/Crafton Park-before/2.jpeg",
      "/images/Crafton Park-before/3.jpeg",
      "/images/Crafton Park-before/4.jpeg",
      "/images/Crafton Park-before/5.jpeg",
      "/images/Crafton Park-before/6.jpeg",
      "/images/Crafton Park-before/IMG_0374.jpeg",
      "/images/Crafton Park-before/IMG_0380.jpeg",
      "/images/Crafton Park-before/IMG_0398.jpeg",
      "/images/Crafton Park-before/IMG_0444.jpeg",
      "/images/Crafton Park-before/IMG_0466.jpeg",
    ],
    afterImgs: [
      "/images/Crafton Park-after/IMG_1236.jpeg",
      //"/images/Crafton Park-after/0.jpeg",
      "/images/Crafton Park-after/IMG_5441.jpeg",
    ],
  },
  {
    title: "Hartsfield Dr",
    location: "WAKE FOREST, NC",
    tagline: "From Bare Bones to Beautiful Home",
    description:
      "Nearly a tear-down, this house received a full structural and cosmetic revival: new foundation, subfloors, insulation, roof, windows, HVAC, bathrooms, kitchen, lighting, decks, and landscaping. It’s now as solid as it is stylish!",
    beforeImgs: [
      "/images/Hartsfield-before/1.jpeg",
      "/images/Hartsfield-before/2.jpeg",
      "/images/Hartsfield-before/3.jpeg",
      "/images/Hartsfield-before/4.jpeg",
      "/images/Hartsfield-before/6.jpeg",
      "/images/Hartsfield-before/7.jpeg",
      "/images/Hartsfield-before/8.jpeg",
      "/images/Hartsfield-before/9.jpeg",
      "/images/Hartsfield-before/10.jpeg",
      "/images/Hartsfield-before/11.jpeg",
      "/images/Hartsfield-before/12.jpeg",
      "/images/Hartsfield-before/13.jpeg",
      "/images/Hartsfield-before/14.jpeg",
      "/images/Hartsfield-before/15.jpeg",
      "/images/Hartsfield-before/16.jpeg",
      "/images/Hartsfield-before/17.jpeg",
      "/images/Hartsfield-before/18.jpeg",
      "/images/Hartsfield-before/19.jpeg",
      "/images/Hartsfield-before/20.jpeg",
      "/images/Hartsfield-before/21.jpeg",
    ],
    afterImgs: [
      "/images/Hartsfield-after/0.jpeg",
      "/images/Hartsfield-after/1.jpeg",
      "/images/Hartsfield-after/2.jpeg",
      "/images/Hartsfield-after/3.jpeg",
      "/images/Hartsfield-after/4.jpeg",
      "/images/Hartsfield-after/5.jpeg",
      "/images/Hartsfield-after/6.jpeg",
      //"/images/Hartsfield-after/7.jpeg",
      //"/images/Hartsfield-after/8.jpeg",
      //"/images/Hartsfield-after/9.jpeg",
      "/images/Hartsfield-after/10.jpeg",
      "/images/Hartsfield-after/15.jpeg",
      "/images/Hartsfield-after/20.jpeg",
      //"/images/Hartsfield-after/30.jpeg",
      "/images/Hartsfield-after/40.jpeg",
      "/images/Hartsfield-after/45.jpeg",
      "/images/Hartsfield-after/50.jpeg",
      "/images/Hartsfield-after/55.jpeg",
      //"/images/Hartsfield-after/60.jpeg",
      "/images/Hartsfield-after/65.jpeg",
    ],
  },
  {
    title: "Joel Ct",
    location: "CARY, NC",
    tagline: "Open, Bright, & Modernized for Today",
    description:
      "An outdated 1980s house turned into a modern dream: open kitchen, beautiful hardwoods, updated bathrooms, and lush landscaping. The result is a cheerful, open home perfect for modern living.",
    beforeImgs: [
      "/images/Joel-before/7.jpeg",
      "/images/Joel-before/3.jpeg",
      "/images/Joel-before/2.jpeg",
      "/images/Joel-before/4.jpeg",
      "/images/Joel-before/5.jpeg",
      "/images/Joel-before/6.jpeg",
      "/images/Joel-before/1.jpeg",
    ],
    afterImgs: [
      "/images/Joel-after/1.jpeg",
      //"/images/Joel-after/2.jpeg",
      "/images/Joel-after/5.jpeg",
      "/images/Joel-after/6.jpeg",
      "/images/Joel-after/7.jpeg",
      "/images/Joel-after/8.jpeg",
      "/images/Joel-after/9.jpeg",
      "/images/Joel-after/10.jpeg",
      "/images/Joel-after/11.jpeg",
      "/images/Joel-after/3.jpeg",
      "/images/Joel-after/4.jpeg",
    ],
  },
  {
    title: "Caniff Ln",
    location: "CARY, NC",
    tagline: "Luxury Finishes, Stunning Outdoor Living",
    description:
      "We gave this house the “wow” factor: elegant hardwood floors, sleek kitchen, modern lighting, spa bathrooms, and an inviting outdoor patio with landscaping for seamless indoor-outdoor living.",
    beforeImgs: [
      "/images/Caniff-before/1.jpeg",
      "/images/Caniff-before/4.jpeg",
      "/images/Caniff-before/5.jpeg",
      "/images/Caniff-before/6.jpeg",
      "/images/Caniff-before/7.jpeg",
      "/images/Caniff-before/10.jpeg",
      "/images/Caniff-before/2.jpeg",
      "/images/Caniff-before/3.jpeg",
      "/images/Caniff-before/8.jpeg",
      "/images/Caniff-before/9.jpeg",
    ],
    afterImgs: [
      "/images/Caniff-after/0.jpeg",
      "/images/Caniff-after/1.jpeg",
      "/images/Caniff-after/2.jpeg",
      "/images/Caniff-after/3.jpeg",
      "/images/Caniff-after/4.jpeg",
      "/images/Caniff-after/5.jpeg",
      "/images/Caniff-after/6.jpeg",
      "/images/Caniff-after/7.jpeg",
      //"/images/Caniff-after/8.jpeg",
      "/images/Caniff-after/9.jpeg",
      "/images/Caniff-after/10.jpeg",
      "/images/Caniff-after/11.jpeg",
      "/images/Caniff-after/12.jpeg",
      "/images/Caniff-after/13.jpeg",
      "/images/Caniff-after/14.jpeg",
      "/images/Caniff-after/15.jpeg",
      "/images/Caniff-after/16.jpeg",
      "/images/Caniff-after/17.jpeg",
    ],
  },
  {
    title: "Wyman Pl",
    location: "DURHAM, NC",
    tagline: "A Modern Home Built for Entertaining",
    description:
      "We transformed a Durham ranch into a modern, open space: added a bedroom and bath, installed new hardwood floors, private fencing, and a new deck with indoor-outdoor flow for great gatherings.",
    beforeImgs: [
      "/images/Wyman-before/1.jpeg",
      "/images/Wyman-before/2.jpeg",
      "/images/Wyman-before/3.jpeg",
      "/images/Wyman-before/4.jpeg",
      "/images/Wyman-before/5.jpeg",
      "/images/Wyman-before/6.jpeg",
      "/images/Wyman-before/7.jpeg",
      "/images/Wyman-before/8.jpeg",
      "/images/Wyman-before/9.jpeg",
      "/images/Wyman-before/10.jpeg",
    ],
    afterImgs: [
      "/images/Wyman-after/1.jpeg",
      //"/images/Wyman-after/2.jpeg",
      "/images/Wyman-after/3.jpeg",
      "/images/Wyman-after/4.jpeg",
      "/images/Wyman-after/5.jpeg",
      "/images/Wyman-after/6.jpeg",
      "/images/Wyman-after/7.jpeg",
      "/images/Wyman-after/8.jpeg",
      "/images/Wyman-after/9.jpeg",
      "/images/Wyman-after/10.jpeg",
      "/images/Wyman-after/11.jpeg",
      "/images/Wyman-after/12.jpeg",
      //"/images/Wyman-after/13.jpeg",
    ],
  },
  {
    title: "Ellynn Dr",
    location: "CARY, NC",
    tagline: "Completely Customized, Just for You",
    description:
      "From outdated to outstanding—this Cary home now features new layouts, bright bedrooms, custom closets, chef’s kitchen, and even a stunning accordion glass door for true indoor-outdoor living.",
    beforeImgs: [
     "/images/Ellynn-before/1.jpeg",
"/images/Ellynn-before/2.jpeg",
"/images/Ellynn-before/3.jpeg",
"/images/Ellynn-before/4.jpeg",
"/images/Ellynn-before/5.jpeg",
"/images/Ellynn-before/6.jpeg",
"/images/Ellynn-before/7.jpeg",
"/images/Ellynn-before/8.jpeg",
"/images/Ellynn-before/9.jpeg",
"/images/Ellynn-before/10.jpeg",
"/images/Ellynn-before/11.jpeg",
"/images/Ellynn-before/12.jpeg",
"/images/Ellynn-before/13.jpeg",
"/images/Ellynn-before/14.jpeg",
"/images/Ellynn-before/15.jpeg",

    ],
    afterImgs: [
      "/images/Ellynn-after/1.jpeg",
    ],
  },
  {
    title: "New Hope Church Rd",
    location: "RALEIGH, NC",
    tagline: "Future-Ready with Style",
    description:
      "We fully reimagined this Raleigh ranch—adding a carport, new kitchen and baths, laundry, private office, open concept, and fully encapsulated crawl space. Everything’s designed for easy, stylish, modern living.",
    beforeImgs: [
      "/images/New Hope Church-before/09b2c129d454e860829873d946ac5e50-cc_ft_1536.webp",
      "/images/New Hope Church-before/0a7d7cfa7d39f604e32572eae4682063-cc_ft_768.webp",
      "/images/New Hope Church-before/210b1251829c333bad0f652b3d0efe89-cc_ft_768.webp",
      "/images/New Hope Church-before/3cb8192a7a97f46e5720d771f1924b32-cc_ft_768.webp",
      "/images/New Hope Church-before/4906b2b012bb70e1136b433b257c25bd-cc_ft_1536.webp",
      "/images/New Hope Church-before/61e050aec3a28a036a1888ae2ba5cd57-cc_ft_768.webp",
      "/images/New Hope Church-before/8c6fd560abf0a7ff020f9a05ce50b50b-cc_ft_1536.webp",
      "/images/New Hope Church-before/a90981eb1505a1d4d33841f67e1f4d7a-cc_ft_768.webp",
      "/images/New Hope Church-before/b5f07316d7dcd86ca5ae3cdd15050208-cc_ft_768.webp",
      "/images/New Hope Church-before/b90be264e066360bd93d12679f9deaf9-cc_ft_1536.webp",
      "/images/New Hope Church-before/c683d7d840080f9197226472e7e94391-cc_ft_1536.webp",
      "/images/New Hope Church-before/f161cdff3842bd353615774746437d5c-cc_ft_1536.webp",
    ],
    afterImgs: [
      "/images/New Hope Church-after/1.jpeg",
    ],
  },
];
